#ifndef UVOS_MPU9250_CONFIG_H
#define UVOS_MPU9250_CONFIG_H

#include "mpugyroaccelsettings.h"
#include "uvos_mpu9250.h"

#define UVOS_MPU9250_CONFIG_MAP_GYROSCALE(x) \
  (x == MPUGYROACCELSETTINGS_GYROSCALE_SCALE_250 ? UVOS_MPU9250_SCALE_250_DEG : \
   x == MPUGYROACCELSETTINGS_GYROSCALE_SCALE_500 ? UVOS_MPU9250_SCALE_500_DEG : \
   x == MPUGYROACCELSETTINGS_GYROSCALE_SCALE_1000 ? UVOS_MPU9250_SCALE_1000_DEG : \
   UVOS_MPU9250_SCALE_2000_DEG)

#define UVOS_MPU9250_CONFIG_MAP_ACCELSCALE(x) \
  (x == MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_2G ? UVOS_MPU9250_ACCEL_2G : \
   x == MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_4G ? UVOS_MPU9250_ACCEL_4G : \
   x == MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_16G ? UVOS_MPU9250_ACCEL_16G : \
   UVOS_MPU9250_ACCEL_8G)

#define UVOS_MPU9250_CONFIG_MAP_FILTERSETTING(x) \
  (x == MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_188_HZ ? UVOS_MPU9250_LOWPASS_188_HZ : \
   x == MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_98_HZ ? UVOS_MPU9250_LOWPASS_98_HZ : \
   x == MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_42_HZ ? UVOS_MPU9250_LOWPASS_42_HZ : \
   x == MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_20_HZ ? UVOS_MPU9250_LOWPASS_20_HZ : \
   x == MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_10_HZ ? UVOS_MPU9250_LOWPASS_10_HZ : \
   x == MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_5_HZ ? UVOS_MPU9250_LOWPASS_5_HZ : \
   UVOS_MPU9250_LOWPASS_256_HZ)
/**
 * @brief Updates MPU9250 config based on MPUGyroAccelSettings UAVO
 * @returns 0 if succeed or -1 otherwise
 */
// int32_t UVOS_MPU9250_CONFIG_Configure()
// {
//   MPUGyroAccelSettingsInitialize();
//   MPUGyroAccelSettingsData mpuSettings;
//   MPUGyroAccelSettingsGet( &mpuSettings );
//   return UVOS_MPU9250_ConfigureRanges(
//            UVOS_MPU9250_CONFIG_MAP_GYROSCALE( mpuSettings.GyroScale ),
//            UVOS_MPU9250_CONFIG_MAP_ACCELSCALE( mpuSettings.AccelScale ),
//            UVOS_MPU9250_CONFIG_MAP_FILTERSETTING( mpuSettings.FilterSetting )
//          );
// }

#endif /* UVOS_MPU9250_CONFIG_H */
